Repository mirakst/P3-Project, pull requests merged in 2021-11, with the labels that each got.

#76 Merge healthReportWindow into dashboardUI
  DashboardFrontend/App.xaml
  DashboardFrontend/DashboardFrontend.csproj
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml.cs
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
Labels: UI

#78 Feature/validation report window merge into Feature/dashboardUI
  DashboardFrontend/App.xaml
  DashboardFrontend/App.xaml.cs
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml.cs
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
Labels: UI

#92 Updating feature/design-update with newer dashboardUI
  DashboardFrontend/DetachedWindows/LogDetached.xaml
Labels: UI

#96 Feature/performance monitoring merge into feature/dashboardUI
  DashboardFrontend/App.xaml
  DashboardFrontend/CustomLabelProvider.cs
  DashboardFrontend/DetachedWindows/ConnectDBDialog.xaml
  DashboardFrontend/DetachedWindows/ConnectDBDialog.xaml.cs
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml.cs
  DashboardFrontend/DetachedWindows/LogDetached.xaml
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml
  DashboardFrontend/DictionaryChart.xaml
  DashboardFrontend/HealthReportMonitoring.cs
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
Labels: programming, UI

#97 Feature/design-update merge into feature/dashboardUI
  DashboardBackend/DashboardBackend.csproj
  DashboardFrontend/App.xaml
  DashboardFrontend/DashboardFrontend.csproj
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml
  DashboardFrontend/DetachedWindows/LogDetached.xaml
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml.cs
  DashboardFrontend/Icons/Cog.png
  DashboardFrontend/Icons/Detach.png
  DashboardFrontend/Icons/Error.png
  DashboardFrontend/Icons/Fatal.png
  DashboardFrontend/Icons/Filter.png
  DashboardFrontend/Icons/Info.png
  DashboardFrontend/Icons/Magnifyingglass.png
  DashboardFrontend/Icons/Start.png
  DashboardFrontend/Icons/Warn.png
  DashboardFrontend/Icons/Warning.png
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
  DashboardFrontend/StyleResources/DictionaryButtons.xaml
  DashboardFrontend/StyleResources/DictionaryChart.xaml
  DashboardFrontend/StyleResources/DictionaryGeneral.xaml
  DashboardFrontend/StyleResources/DictionaryListView.xaml
  DashboardFrontend/StyleResources/DictionaryTab.xaml
Labels: enhancement, Design, UI

#99 Feature/dashboard UI settings
  DashboardFrontend/DashboardFrontend.csproj
  DashboardFrontend/DetachedWindows/NewProfileWindow.xaml
  DashboardFrontend/DetachedWindows/NewProfileWindow.xaml.cs
  DashboardFrontend/DetachedWindows/SettingsWindow.xaml
  DashboardFrontend/DetachedWindows/SettingsWindow.xaml.cs
  DashboardFrontend/MainWindow.xaml.cs
  DashboardFrontend/Settings/IUserSettings.cs
  DashboardFrontend/Settings/Profile.cs
  DashboardFrontend/Settings/UserSettings.cs
  DashboardFrontend/ValueConverters/ProfileConverter.cs
  DashboardFrontend/ValueConverters/StringToIntConverter.cs
  DashboardFrontend/ViewModels/UserSettingsViewModel.cs
  SW305.sln
Labels: programming

#109 Feature/new graph library test
  DashboardFrontend/App.xaml
  DashboardFrontend/DashboardFrontend.csproj
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml
  DashboardFrontend/DetachedWindows/HealthReportDetached.xaml.cs
  DashboardFrontend/DetachedWindows/ValidationReportDetached.xaml
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
  DashboardFrontend/StyleResources/CustomLabelProvider.cs
  DashboardFrontend/StyleResources/DictionaryChart.xaml
  DashboardFrontend/ViewModels/LiveChartViewModel.cs
  DashboardFrontend/ViewModels/NetworkViewModel.cs
  DashboardFrontend/ViewModels/PerformanceViewModel.cs
Labels: enhancement, programming, UI

#145 Loading Animation
  DashboardFrontend/App.xaml
  DashboardFrontend/Controller.cs
  DashboardFrontend/DetachedWindows/ConnectDBDialog.xaml
  DashboardFrontend/DetachedWindows/ConnectDBDialog.xaml.cs
  DashboardFrontend/MainWindow.xaml
  DashboardFrontend/MainWindow.xaml.cs
  DashboardFrontend/StyleResources/DictionaryAnimations.xaml
  DashboardFrontend/StyleResources/DictionaryGeneral.xaml
Labels: programming
